# Generated by Django 5.1.4 on 2024-12-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bdescription',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bgenres',
        ),
    ]
